services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
  prometheus:  
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom-data:/prometheus
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always
  ping-exporter:
    image: czerwonk/ping_exporter
    container_name: ping-exporter
    ports:
      - 9427:9427
    restart: always
    volumes:
      - ./ping-exporter:/config:ro
  loki:
    container_name: loki
    image: grafana/loki:3.0.1
    ports:
      - 3100:3100
    volumes:
      - loki-storage:/loki
      - ./loki:/etc/loki
    restart: alwaysz
    command: -config.file=/etc/loki/loki-local-conf.yaml
 
volumes:
  grafana-storage: {}
  prom-data: {}
  loki-storage: {}
