targets:
  - 8.8.8.8
  - 1.1.1.1
  - 104.160.154.59

dns:
  refresh: 2m15s
  nameserver: 1.1.1.1

ping:
  interval: 2s
  timeout: 3s
  history-size: 42
  payload-size: 120

options:
  disableIPv6: true
